[project]
name = "python-pet-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.123.8",
    "google-genai>=1.53.0",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.38.0",
]
